spring.datasource.url=jdbc:postgresql://localhost:5432/cookie_jar
spring.datasource.username=dev
spring.datasource.password=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}

# cloudinary.cloud-name=dnqfsoywp
# cloudinary.api-key=584212655592545
# cloudinary.api-secret=d5IbVHBisMrHcJAXe9Bx1FFR_NU